version: '3.8'

services:
  map:
    image: ghcr.io/autowarefoundation/autoware:universe-localization-mapping
    container_name: autoware-map
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    volumes:
      - ${MAP_PATH:-$HOME/autoware_map}:/autoware_map:ro
    networks:
      - autoware-net
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch autoware_launch tier4_map_component.launch.xml
      lanelet2_map_file:=${LANELET2_MAP_FILE:-lanelet2_map.osm}
      map_path:=/autoware_map
      pointcloud_map_file:=${POINTCLOUD_MAP_FILE:-pointcloud_map.pcd}
      "
    restart: unless-stopped

  planning:
    image: ghcr.io/autowarefoundation/autoware:universe-planning-control
    container_name: autoware-planning
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    networks:
      - autoware-net
    depends_on:
      - map
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch autoware_launch tier4_planning_component.launch.xml
      enable_all_modules_auto_mode:=${ENABLE_ALL_MODULES_AUTO_MODE:-false}
      is_simulation:=${IS_SIMULATION:-true}
      module_preset:=${PLANNING_MODULE_PRESET:-default}
      pointcloud_container_name:=${POINTCLOUD_CONTAINER_NAME:-pointcloud_container}
      vehicle_model:=${VEHICLE_MODEL:-sample_vehicle}
      "
    restart: unless-stopped

  control:
    image: ghcr.io/autowarefoundation/autoware:universe-planning-control
    container_name: autoware-control
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    networks:
      - autoware-net
    depends_on:
      - planning
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch autoware_launch tier4_control_component.launch.xml
      check_external_emergency_heartbeat:=${CHECK_EXTERNAL_EMERGENCY_HEARTBEAT:-false}
      lateral_controller_mode:=${LATERAL_CONTROLLER_MODE:-mpc}
      longitudinal_controller_mode:=${LONGITUDINAL_CONTROLLER_MODE:-pid}
      module_preset:=${CONTROL_MODULE_PRESET:-default}
      vehicle_id:=${VEHICLE_ID:-default}
      vehicle_model:=${VEHICLE_MODEL:-sample_vehicle}
      "
    restart: unless-stopped

  vehicle:
    image: ghcr.io/autowarefoundation/autoware:universe-vehicle-system
    container_name: autoware-vehicle
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    networks:
      - autoware-net
    depends_on:
      - control
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch tier4_vehicle_launch vehicle.launch.xml
      vehicle_model:=${VEHICLE_MODEL:-sample_vehicle}
      sensor_model:=${SENSOR_MODEL:-sample_sensor_kit}
      vehicle_id:=${VEHICLE_ID:-default}
      launch_vehicle_interface:=${LAUNCH_VEHICLE_INTERFACE:-true}
      raw_vehicle_cmd_converter_param_path:=/opt/autoware/share/autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
      "
    restart: unless-stopped

  system:
    image: ghcr.io/autowarefoundation/autoware:universe-vehicle-system
    container_name: autoware-system
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    networks:
      - autoware-net
    depends_on:
      - map
      - planning
      - control
      - vehicle
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch autoware_launch tier4_system_component.launch.xml
      system_run_mode:=${SYSTEM_RUN_MODE:-planning_simulation}
      launch_system_monitor:=${LAUNCH_SYSTEM_MONITOR:-false}
      launch_dummy_diag_publisher:=${LAUNCH_DUMMY_DIAG_PUBLISHER:-true}
      sensor_model:=${SENSOR_MODEL:-sample_sensor_kit}
      "
    restart: unless-stopped

  simulator:
    image: ghcr.io/autowarefoundation/autoware:universe
    container_name: autoware-simulator
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    networks:
      - autoware-net
    depends_on:
      - map
      - system
      - vehicle
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch autoware_launch tier4_simulator_component.launch.xml
      launch_dummy_perception:=${LAUNCH_DUMMY_PERCEPTION:-true}
      launch_dummy_vehicle:=${LAUNCH_DUMMY_VEHICLE:-true}
      localization_sim_mode:=${LOCALIZATION_SIM_MODE:-api}
      launch_dummy_doors:=${LAUNCH_DUMMY_DOORS:-true}
      launch_scenario_simulator_v2_adapter:=${LAUNCH_SCENARIO_SIMULATOR_V2_ADAPTER:-false}
      perception/enable_detection_failure:=${PERCEPTION_ENABLE_DETECTION_FAILURE:-true}
      perception/enable_object_recognition:=${PERCEPTION_ENABLE_OBJECT_RECOGNITION:-true}
      perception/enable_traffic_light:=${PERCEPTION_ENABLE_TRAFFIC_LIGHT:-false}
      perception/use_base_link_z:=${PERCEPTION_USE_BASE_LINK_Z:-true}
      sensing/visible_range:=${SENSING_VISIBLE_RANGE:-300.0}
      vehicle_model:=${VEHICLE_MODEL:-sample_vehicle}
      initial_engage_state:=${INITIAL_ENGAGE_STATE:-true}
      vehicle_info_param_file:=/opt/autoware/share/${VEHICLE_MODEL:-sample_vehicle}_description/config/vehicle_info.param.yaml
      raw_vehicle_cmd_converter_param_path:=/opt/autoware/share/autoware_launch/config/vehicle/raw_vehicle_cmd_converter/raw_vehicle_cmd_converter.param.yaml
      "
    restart: unless-stopped

  api:
    image: ghcr.io/autowarefoundation/autoware:universe
    container_name: autoware-api
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
    networks:
      - autoware-net
    depends_on:
      - system
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 launch autoware_launch tier4_autoware_api_component.launch.xml
      "
    restart: unless-stopped

  visualization:
    image: ghcr.io/autowarefoundation/autoware:universe-visualization
    container_name: autoware-visualization
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - USE_SIM_TIME=${USE_SIM_TIME:-true}
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORMTHEME=qt5ct
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - autoware-net
    depends_on:
      - map
      - planning
      - control
      - simulator
    profiles:
      - visualization
    command: >
      bash -c "
      source /opt/autoware/setup.bash &&
      ros2 run rviz2 rviz2 -d /opt/autoware/share/autoware_launch/rviz/${RVIZ_CONFIG_NAME:-autoware.rviz}
      "
    restart: unless-stopped

networks:
  autoware-net:
    driver: bridge
